name: RiteshGohil
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131231'
    - '#eedba3'
    - '#c1aa8b'
    - '#9f897c'
    - '#343041'
  brandStrength: 1
  lightness: 0.9210687852464616
  saturation: 0
  rhythmicContrast: 1
purpose: []
