name: RiteshGohil
favicon: null
layout_spectrum: 0.6228273247834295
typography_spectrum: 0.5400854386389256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9009929227177054
  lightness: 0.9210687852464616
  saturation: 0.0729805282317102
  rhythmicContrast: 0.8579699213150889
purpose: []
